name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          path: ./a
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: Checkout OntarioVerify
        uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          path: ./b
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: CD
        run : cd ../ && ls -al
     # - name: PREPARE
     #   run: ./prepare.pl
     # - name: CD
     #   run: cd VerifyOpenSource && ls -al
     # - name: CD OntarioVerify
     #   run: cd Verify && ls -al
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
