name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          path: ./VerifyOpenSource
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: CD
        run : cd VerifyOpenSource && ls -al
      - name: PREPARE
        run: ./VerifyOpenSource/prepare.pl
     # - uses: actions/checkout@v2
     #   with:
     #     repository: ongov/OntarioVerify
     #     path: ./Verify
     #     ref: refs/heads/main
     #     token: ${{ secrets.PAT }}
     # - name: CD
     #   run: cd VerifyOpenSource && ls -al
     # - name: CD OntarioVerify
     #   run: cd Verify && ls -al
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
