name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          path: ./a
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: Checkout OntarioVerify
        uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          path: ./b
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: CD
        run : ls -al ./a && ls -al ./b
      - name: COPY
        run: |
           cp -R ./b ./a/OntarioVerify && \
           rm -rf ./a/OntarioVerify/.git && \
           rm -rf ./a/OntarioVerify/.github && \
           ls -al ./a && \
           cp -R ./a/openverify ./a/OntarioVerify && \
           ls -al ./a/OntarioVerify && \
           ./a/OntarioVerify/openverify/transform.linux.sh
     # - name: PREPARE
     #   run: ./prepare.pl
     # - name: CD
     #   run: cd VerifyOpenSource && ls -al
     # - name: CD OntarioVerify
     #   run: cd Verify && ls -al
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
