name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ongov/Verify
          path: ./Verify
          ref: main
      #- uses: actions/checkout@v2
        #with:
        #  repo-token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Run Prepare
      #  run: ./prepare.pl
      #- name: Git hub parameters
      #  run: echo "${GITHUB_ACTOR}"
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
