name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule add https://github.com/ongov/OntarioVerify
      - name: CD
        run : ls -al
     # - name: PREPARE
     #   run: ./prepare.pl
     # - uses: actions/checkout@v2
     #   with:
     #     repository: ongov/OntarioVerify
     #     path: ./Verify
     #     ref: refs/heads/main
     #     token: ${{ secrets.PAT }}
     # - name: CD
     #   run: cd VerifyOpenSource && ls -al
     # - name: CD OntarioVerify
     #   run: cd Verify && ls -al
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
