name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          path: ./a
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: Checkout OntarioVerify
        uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          path: ./b
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: LIST
        run: ls -al ./a && ls -al ./b
      - name: RUN
        run: |
          cp -R ./b ./a/OntarioVerify && \
          rm -rf ./a/OntarioVerify/.git && \
          rm -rf ./a/OntarioVerify/.github && \
          ls -al ./a && \
          cp -R ./a/openverify ./a/OntarioVerify && \
          ls -al ./a/OntarioVerify/openverify
      -name: PUSH
        run: git remote -v
          
