name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          path: ./VerifyOpenSource
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: Checkout OntarioVerify
        uses: actions/checkout@v2
        with:
          repository: ongov/OntarioVerify
          path: ./OpenVerify
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: LIST
        run: ls -al ./VerifyOpenSource && ls -al ./OpenVerify
      - name: RUN
        run: |
          cp -R ./OpenVerify ./VerifyOpenSource/OntarioVerify && \
          rm -rf ./VerifyOpenSource/OpenVerify/.git && \
          rm -rf ./VerifyOpenSource/OpenVerify/.github && \
          ls -al ./VerifyOpenSource && \
          cp -R ./VerifyOpenSource/openverify ./VerifyOpenSource/OpenVerify && \
          ./VerifyOpenSource/OpenVerify/openverify/transform.linux.sh && \
          ./VerifyOpenSource/OpenVerify/openverify/transform.linux.sh && \
          ./VerifyOpenSource/OpenVerify/openverify/transform.linux.sh && \
          rm -rf ./VerifyOpenSource/OpenVerify/openverify
      - name: PUSH
        run: |
             cd ./VerifyOpenSource && \
             git switch -C test1 && \
             git add . && \
             git commit -m "added OntarioVerify" && \
             git push -d origin test1 && \
             git push -u origin test1
          
