name: OpnSrc1
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - uses: actions/checkout@v2
        with:
          repository: sanchilon/VerifyOpenSource
          ref: refs/heads/main
          token: ${{ secrets.PAT }}
      - name: RUN
        run: |
          rm -rf OntarioVerify && \
          git rm --cached -rf OntarioVerify  && \
          rm -rf .git/modules && rm -f ./gitmodules  && \
          git submodule add https://github.com/ongov/OntarioVerify  && \
          cd OntarioVerify  && \
          git switch -C main origin/main  && \
          git pull --rebase origin main  && \
          rm -rf .git && \
          rm -rf .github && \
          cp -R ../openverify . && \
          ./openverify/transform.linux.sh && \
          ./openverify/transform.linux.sh && \
          ./openverify/transform.linux.sh && \
          rm -rf openverify
