# This is a basic workflow to help you get started with Actions

name: Prepare1

# Controls when the workflow will run
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepare :
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: CONFIG
        run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      - name: ADDGITUSER
        run: |
          echo "https://$GITHUB_ACTOR:${{ secrets.PAT_GIST}}@github.com" > $HOME/.git-credentials
          git config --global credential.helper "store --file $HOME/.git-credentials"
      - name: CLONE VERIFYOPEN
        run: git clone https://github.com/sanchilon/VerifyOpenSource
      - name: PREPARE
        run: cd VerifyOpenSource && ./prepare.pl

    
