name: Prepare
on:
  workflow_dispatch:

jobs:
  opensrc:
    runs-on: ubuntu-latest
    environment: WF_Env
    steps:
      #- name: CONFIG
      #  run: git config --global user.name "sanchilon" && git config --global user.email "sandeep.chiluveru@ontario.ca"
      #- name: CHECKOUT
      #  uses: actions/checkout@v2
      #  with:
      #    repository: sanchilon/VerifyOpenSource
      #    ref: refs/heads/main
      #    token: ${{ secrets.PAT }}
      - name: CLEAR GITHUB TOKEN
        run : export GITHUB_TOKEN=
      - name: TOUCHFILE
        run: |
           cat < EOF > tt
           "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"
           EOF
      - name: USE GH AS CREDENTIAL HELPER
        run: |
          git config --global 'credential.https://github.com.helper' ''
          git config --global --add 'credential.https://github.com.helper' '!gh auth git-credential'
      - name: CLI
        run: gh auth login --with-token < tt
      #- name: RUN
      #  run: ./prepare.pl
